version: '3.1'

services:
  db:
    image: kapua/kapua-sql:${IMAGE_VERSION}
    ports:
      - 8181:8181
      - 3306:3306
  es:
    image: elasticsearch:5.4.0
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - cluster.name=kapua-datastore
      - discovery.type=single-node
      - transport.host=_site_
      - transport.ping_schedule=-1
      - transport.tcp.connect_timeout=30s
  events-broker:
    image: kapua/kapua-events-broker:${IMAGE_VERSION}
    ports:
      - 5672:5672
  broker:
    image: kapua/kapua-broker:${IMAGE_VERSION}
    ports:
      - 1883:1883
      - 8883:8883
      - 61614:61614
    depends_on:
      - db
      - es
      - events-broker
    environment:
      - KAPUA_DISABLE_SSL
      - KAPUA_CRT
      - KAPUA_CA
      - KAPUA_KEY
      - KAPUA_KEY_PASSWORD
      - KAPUA_KEYSTORE
      - KAPUA_KEYSTORE_PASSWORD
  kapua-console:
    image: kapua/kapua-console:${IMAGE_VERSION}
    ports:
      - 8080:8080
      - 8443:8443
    depends_on:
      - broker
      - db
      - es
      - events-broker
    environment:
      - KAPUA_DISABLE_SSL
      - KAPUA_CA
      - KAPUA_CRT
      - KAPUA_KEY
      - KAPUA_KEY_PASSWORD
      - KAPUA_KEYSTORE
      - KAPUA_KEYSTORE_PASSWORD
      - JAVA_OPTS=-Dcommons.db.schema.update=true 
               -Dcommons.db.connection.host=$SQL_DB_ADDR
               -Dcommons.db.connection.port=$SQL_DB_PORT
               -Dbroker.host=$BROKER_ADDR
               -Ddatastore.elasticsearch.nodes=$DATASTORE_ADDR
               -Ddatastore.elasticsearch.port=$DATASTORE_PORT
               -Ddatastore.client.class=$DATASTORE_CLIENT
               -Dcommons.eventbus.url=$SERVICE_BROKER_ADDR
               -Dcertificate.jwt.private.key=file:///var/opt/jetty/key.pk8
               -Dcertificate.jwt.certificate=file:///var/opt/jetty/cert.pem
               -Dsso.provider=generic
               -Dsso.openid.client.id=@!1DA9.BCB4.7B32.B721!0001!022F.4EED!0008!59B0.990E.3051.CA54
               -Dsso.openid.client.secret=ChsQTJUnCU7SJtBLFYHpvnio
               -Dsso.site.home.uri=http://portal.solidsense.tk:8080/console.jsp
               -Dsso.openid.redirect.uri=http://portal.solidsense.tk:8080/sso/callback
               -Dsso.generic.openid.server.endpoint.auth=https://gluu-auth.tk/oxauth/restv1/authorize
               -Dsso.generic.openid.server.endpoint.token=https://gluu-auth.tk/oxauth/restv1/token
               -Dconsole.site.home.uri=http://portal.solidsense.tk:8080/console.jsp
               -Dconsole.sso.enabled=true
               -Dconsole.sso.redirect.uri=http://portal.solidsense.tk:8080/sso/callback
               -Dconsole.sso.openid.server.endpoint.auth=https://gluu-auth.tk/oxauth/restv1/authorize
               -Dconsole.sso.openid.server.endpoint.token=https://gluu-auth.tk/oxauth/restv1/token
               -Dconsole.sso.openid.client.id=@!1DA9.BCB4.7B32.B721!0001!022F.4EED!0008!59B0.990E.3051.CA54
               -Djavax.net.ssl.trustStore=/resources/truststore.ks
               -Djavax.net.ssl.trustStorePassword=mflux56
               -Dauthentication.credential.jwt.issuer.allowed=https://gluu-auth.tk
               -Dauthentication.credential.jwt.audience.allowed=@!1DA9.BCB4.7B32.B721!0001!022F.4EED!0008!59B0.990E.3051.CA54
               -Dauto.registration.simple.rootAccount=kapua-sys
               -Dauto.registration.simple.maximumNumberOfChildUsers=1
               -Dauto.registration.simple.accountExpirationDate.days=30
    volumes:
      - ./truststore.ks:/resources/truststore.ks
  kapua-api:
    image: kapua/kapua-api:${IMAGE_VERSION}
    ports:
      - 8081:8080
      - 8444:8443
    depends_on:
      - broker
      - db
      - es
      - events-broker
    environment:
      - KAPUA_DISABLE_SSL
      - KAPUA_CA
      - KAPUA_CRT
      - KAPUA_KEY
      - KAPUA_KEY_PASSWORD
      - KAPUA_KEYSTORE
      - KAPUA_KEYSTORE_PASSWORD
